//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltooid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributions
    {
        public int Id { get; set; }
        public Nullable<int> TabelId { get; set; }
        public Nullable<int> ConferenceId { get; set; }
        public string Topic { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
