//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltooid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScientistsEntities : DbContext
    {
        public ScientistsEntities()
            : base("name=ScientistsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conferences> Conferences { get; set; }
        public virtual DbSet<Contributions> Contributions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<SystemUsers> SystemUsers { get; set; }
    }
}
