//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltooid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUsers()
        {
            this.Contributions = new HashSet<Contributions>();
        }
    
        public int TabelId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Country { get; set; }
        public Nullable<int> Stage { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contributions> Contributions { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Stage Stage1 { get; set; }
    }
}
